version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=tracker

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - AUTH0_DOMAIN=dev-jl4brqjuvbkbm47r.us.auth0.com
      - AUTH0_AUDIENCE=https://tracker.larcom.dev
    depends_on:
      - mongodb

volumes:
  mongodb_data: 